### ISSUE TITLE
bindUiComponent is exported 3 times? not sure if it's a problem...

### ISSUE THREAD

**Issue by luckman212** [mnaoumov/obsidian-dev-utils#1]
I noted here (https://github.com/RainCat1998/obsidian-custom-attachment-location/issues/88) that the obsidian-custom-attachment-location plugin settings does not display the current value of `jpegQuality`, it always shows `0.1`.

I confirmed the data is correctly saved to `data.json`, so this is a display issue. I am not smart enough to figure out where the problem is, but seems to be in this library maybe.

Is it a problem that this `bindUiComponent` function is exported 3 times with differing parameters?

https://github.com/mnaoumov/obsidian-dev-utils/blob/967ca31067898feda3935945e4e4454f77a4a92b/src/obsidian/Plugin/UIComponent.ts#L99

https://github.com/mnaoumov/obsidian-dev-utils/blob/967ca31067898feda3935945e4e4454f77a4a92b/src/obsidian/Plugin/UIComponent.ts#L129

https://github.com/mnaoumov/obsidian-dev-utils/blob/967ca31067898feda3935945e4e4454f77a4a92b/src/obsidian/Plugin/UIComponent.ts#L159

**Comment by mnaoumov** [comment]
No, it is not an issue. That's [Function Overloads](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads)

**Comment by mnaoumov** [comment]
The three `bindUiComponent` declarations are TypeScript function overloads. That is intended, not a bug.
