### ISSUE TITLE
[FR] Set sourceRoot in esbuild?

### ISSUE THREAD

**Issue by baodrate** [mnaoumov/obsidian-dev-utils#3]
### Description

More of a question than a feature request. I'm just curious about your approach and wondering if I'm missing something.

### Details

n/a

### Desired Behavior

Why don't we set the [sourceRoot field in the source map](https://esbuild.github.io/api/#source-root)?

```diff
diff --git a/src/scripts/esbuild/ObsidianPluginBuilder.ts b/src/scripts/esbuild/ObsidianPluginBuilder.ts
index 59d75c0..1cc7d86 100644
--- a/src/scripts/esbuild/ObsidianPluginBuilder.ts
+++ b/src/scripts/esbuild/ObsidianPluginBuilder.ts
@@ -151,11 +151,11 @@ export async function buildObsidianPlugin(options: BuildObsidianPluginOptions):
     platform: 'node',
     plugins: [
       preprocessPlugin(),
-      fixSourceMapsPlugin(isProductionBuild, distPath, pluginName),
       ...customEsbuildPlugins,
       copyToObsidianPluginsFolderPlugin(isProductionBuild, distDir, obsidianConfigDir, pluginName)
     ],
     sourcemap: isProductionBuild ? false : 'inline',
+    sourceRoot: `app://obsidian.md/plugin:${pluginName}/`,
     target: 'esnext',
     treeShaking: true
   };
```

It has the same effect of differentiating the source files of each plugin, without having to parse and edit the generated `sourceMappingURL`

Is there a downside to this approach?

### Current Behavior

Currently we replace the `sourceMappingURL` that is generated by esbuild (or rather, tsc?) by decoding it and editing each item in `sources`

https://github.com/mnaoumov/obsidian-dev-utils/blob/644356a1e423d10904d3af9e8aef867c8d94d005/src/scripts/esbuild/fixSourceMapsPlugin.ts#L52-L64

to be prepended with `app://obsidian.md/plugin:${pluginName}/`

https://github.com/mnaoumov/obsidian-dev-utils/blob/644356a1e423d10904d3af9e8aef867c8d94d005/src/scripts/esbuild/fixSourceMapsPlugin.ts#L38-L42

### Attachments

n/a

### Confirmations

- [X] I attached a video showing the current behavior
- [X] I attached a sample vault where the desired Feature Request could be applied
- [X] I have tested the issue with the latest version
- [X] I have checked for existing Feature Requests

**Comment by mnaoumov** [comment]
@baodrate thanks for your suggestion, I tried it before but it doesn't work as expected

1. That's how my code works

```json
{
    "version": 3,
    "sources": [
        "app://obsidian.md/plugin:better-markdown-links/node_modules/obsidian-typings/src/obsidian/implementations/index.ts",
        "app://obsidian.md/plugin:better-markdown-links/node_modules/obsidian-typings/src/obsidian/implementations/PathUtils.ts",
        "..."
    ]
}
```

2. That's how your suggestion works

```json
{
    "version": 3,
    "sources": [
        "../../node_modules/obsidian-typings/src/obsidian/implementations/index.ts",
        "../../node_modules/obsidian-typings/src/obsidian/implementations/PathUtils.ts",
        "..."
    ]
}
```

So as you see, I still have to stick to my version

**Comment by mnaoumov** [comment]
Setting esbuild's `sourceRoot` was tried. It produced relative `../../node_modules/...` sources instead of per-plugin `app://obsidian.md/plugin:<id>/` URLs, so the current source-map rewrite stays.
